mtl: add MicSel support
thesofproject/rimage pull request #101
Opened 2022-06-27 07:39 UTC by RanderWang

Add MicSel config int mtl.toml

Prepare for MicSel support in SOF FW.

2022-06-28 10:10 UTC, lgirdwood approved these changes

2022-06-28 10:10 UTC, lgirdwood commented
@marcinszkudlinski any comments ?

2022-06-28 13:11 UTC, marcinszkudlinski requested changes

2022-06-29 01:18 UTC, RanderWang commented on config/mtl.toml
> +	uuid = "55A88ED5-3D18-46CA-88F1-0EE6EAE9930F"
Do we need to reuse close source fw uuid ?  Driver gets uuid from manifest and doesn't have a copy in driver.

2022-06-29 10:06 UTC, lgirdwood commented on config/mtl.toml
> +	uuid = "55A88ED5-3D18-46CA-88F1-0EE6EAE9930F"
yes, we should use the same UUID.

2022-06-29 14:35 UTC, RanderWang commented on config/mtl.toml
> +	uuid = "55A88ED5-3D18-46CA-88F1-0EE6EAE9930F"
Thanks, updated UUID

2022-06-30 07:52 UTC, marcinszkudlinski approved these changes

2022-07-01 08:52 UTC, merged